### ISSUE TITLE
Git Intro: Clone existing CV repository from GitHub

### ISSUE THREAD

**Issue by codingbootcampseu** [andruuuh/bootcamp-schedule#32]
You will now remove your local CV folder to clone it again from GitHub. 

> While this sound a little strange it's the easiest way to connect your local CV folder to GitHub

- [ ] Add all your local changes to your CV repository on GitHub 
- [ ] Remove your local cv folder
- [ ] Go to your cv repository on GitHub
- [ ] Copy the clone link 
  - Use HTTPS if you haven't configured SSH yet - otherwise use SSH 💡
- [ ] Clone the repository onto your computer (into your coding folder)
 
> 🚨 Heads up where you use the `git clone` command because it will create a new folder including a git repository

**Comment by andruuuh** [comment]
internalized and closed.
